# Generated by Django 2.2.1 on 2019-05-07 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GANADO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('arete', models.CharField(max_length=10)),
                ('siniga', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('propietario', models.CharField(max_length=20)),
                ('ganadera', models.CharField(max_length=20)),
                ('no_padre', models.IntegerField(blank=True, null=True)),
                ('no_madre', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_nacimiento', models.CharField(choices=[('Uníparo', 'Uníparo'), ('Gemelar MH', 'Gemelar MH'), ('Gemelar HH', 'Gemelar HH'), ('Gemelar MM', 'Gemelar MM'), ('Multiple', 'Multiple')], max_length=15)),
                ('tipo_parto', models.CharField(choices=[('Normal', 'Normal'), ('Distónico', 'Distónico'), ('Difícil', 'Difícil'), ('Cesárea', 'Cesárea')], max_length=15)),
                ('localizacion_fierro', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('Vendida', 'Vendida'), ('Viva', 'Viva'), ('Muerta', 'Muerta')], max_length=10)),
                ('galeria_venta', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='Ganado', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HISTORIAL_VENTAS_BOVINO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bovino', models.CharField(default='0000', max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HISTORIAL_VENTAS_CERDOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BITACORA_GANADO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bovino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.GANADO')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
