# Generated by Django 2.1.7 on 2019-05-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTROL_GANADO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arete', models.CharField(max_length=10)),
                ('motivo', models.CharField(choices=[('Pesaje', 'Pesaje'), ('Servicio', 'Servicio')], max_length=15)),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
