# Generated by Django 2.1.7 on 2019-05-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_control_ganado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORIAL_VENTAS_CERDOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CONTROL_GANADO',
        ),
    ]
